# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16f0ceee4ea50220bc4299275695842a"
name = "banner"
handle = "banner-312"
application_url = "https://wrong-mc-basement-acm.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bezekz.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://wrong-mc-basement-acm.trycloudflare.com/auth/callback",
  "https://wrong-mc-basement-acm.trycloudflare.com/auth/shopify/callback",
  "https://wrong-mc-basement-acm.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
