# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "02ab13d1b2dea682602c67d6f0897ec2"
name = "Banner-dev"
handle = "banner-dev-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
